name: CLI Build
on:
  push:
    branches: [main]
jobs:
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: latest
          platform: x64
