name: CLI Build
on:
  push:
    branches: [main]
    workflow_dispatch:

jobs:
  Build nisrom and print firmware info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1.3
        with:
          version: latest
          platform: x64
      - uses: actions/checkout@v4
        with:
          path: 'nissutils'
          repository: 'fenugrec/nissutils'
          submodules: true
      - run: |
          cd nissutils/cli_utils
          sed -i '/^CFLAGS/s/$/ -I md5/' Makefile
          make
      - name: Outputs
        run: |
          ls -la  
          bash nisrom_output.sh
